version: '3.8'

#Docker Networks
networks:
  mainnet:
    driver: bridge

# Workflow
services:
  nuxt_main:
    build:
      context: .
      dockerfile: ./docker/nuxt/Dockerfile
    container_name: nuxt_main
    # volumes:
    #   - ./src:/var/www/html:delegated
    restart: always
    ports:
      - "3000:3000"
    command:
      "pnpm start"
    networks:
      - mainnet